name: Build

on:
  push:
    branches:
      - release

jobs:
  build_unix:
    runs-on: ubuntu-latest

    outputs:
      ytdlp_version: ${{ steps.bump_version.outputs.ytdlp_version }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.8'
    - name: Bump version
      id: bump_version
      run: |
        python devscripts/update-version.py
        make issuetemplates
    - name: Print version
      run: echo "${{ steps.bump_version.outputs.ytdlp_version }}"
    - name: Update master
      run: |
        git config --global user.email "${{ github.event.pusher.email }}"
        git config --global user.name "${{ github.event.pusher.name }}"
        git add -u
        git commit -m "[version] update" -m ":ci skip all"
        git pull --rebase origin ${{ github.event.repository.master_branch }}
        git push origin ${{ github.event.ref }}:${{ github.event.repository.master_branch }}
    - name: Get Changelog
      id: get_changelog
      run: |
        changelog=$(cat Changelog.md | grep -oPz '(?s)### TEST.+?(\r?\n){2,3}(?=###)')
        echo "changelog<<EOF" >> $GITHUB_ENV
        echo "$changelog" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: print changelog
      run: echo "${{ steps.get_changelog.outputs.changelog }}"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump_version.outputs.ytdlp_version }}
        release_name: yt-dlp ${{ steps.bump_version.outputs.ytdlp_version }}
        body: |
          Changelog:
          ${{ env.changelog }}
        draft: false
        prerelease: false
